### ISSUE TITLE
Dll not found at WPF app

### ISSUE THREAD

**Issue by Sash0check** [Ruminoid/Spout.NET#4]
Hello, i'm trying to use your lib in WPF, but have this Error: "System.DllNotFoundException: 'Not found DLL "Libraries/Spout.dll": Module not found. (Exception from HRESULT: 0x8007007E)'". Could you help to me?
I switched platform to x64
Visual Studio 2019, net 4.8

**Comment by ilharp** [comment]
`Spout.dll` is provided by this package and is located under the `Libraries` folder. You need to consider the dll file and other dll dependencies inside `bin` folder as part of the program.

Create a new project, add this package and run `tree /F bin`, you'll see a directory structure like this:

```
└─x64
    └─Debug
        └─net48
            │  CppSharp.AST.dll
            │  CppSharp.dll
            │  CppSharp.Generator.dll
            │  CppSharp.Parser.CLI.dll
            │  CppSharp.Parser.dll
            │  CppSharp.Runtime.dll
            │  MyApp.exe
            │  MyApp.exe.config
            │  MyApp.pdb
            │  OpenGL.Net.dll
            │  Spout.NET.dll
            │  System.Buffers.dll
            │  System.Memory.dll
            │  System.Numerics.Vectors.dll
            │  System.Runtime.CompilerServices.Unsafe.dll
            │
            └─Libraries
                    Spout.dll
```

All files except pdb files are dependencies of this program, please include the entire `bin` folder when distributing the program.

If you have further questions, feel free to leave a comment below.
